GSN = [
		["AK",    "BMR " ], 
		["AK",    "TNA " ], 
		["AT",    "PMR " ], 
		["AT",    "SDPT" ], 
		["AT",    "SMY " ], 
		["BK",    "CMB " ], 
		["BK",    "HUMO" ], 
		["BK",    "MCCM" ], 
		["BK",    "SAO " ], 
		["BK",    "WDC " ], 
		["CI",    "ISA " ], 
		["CI",    "PASC" ], 
		["CU",    "ANWB" ], 
		["CU",    "BBGH" ], 
		["CU",    "BCIP" ], 
		["CU",    "GRGR" ], 
		["CU",    "GRTK" ], 
		["CU",    "GTBY" ], 
		["CU",    "MTDJ" ], 
		["CU",    "SDDR" ], 
		["CU",    "TGUH" ], 
		["ET",    "SWET" ], 
		["GT",    "BDFB" ], 
		["GT",    "BGCA" ], 
		["GT",    "BOSA" ], 
		["GT",    "CPUP" ], 
		["GT",    "DBIC" ], 
		["GT",    "LBTB" ], 
		["GT",    "LPAZ" ], 
		["GT",    "PLCA" ], 
		["GT",    "VNDA" ], 
		["IC",    "BJT " ], 
		["IC",    "ENH " ], 
		["IC",    "HIA " ], 
		["IC",    "KMI " ], 
		["IC",    "LSA " ], 
		["IC",    "MDJ " ], 
		["IC",    "QIZ " ], 
		["IC",    "SSE " ], 
		["IC",    "WMQ " ], 
		["IC",    "XAN " ], 
		["II",    "AAK " ], 
		["II",    "ABKT" ], 
		["II",    "ABPO" ], 
		["II",    "ALE " ], 
		["II",    "ARU " ], 
		["II",    "ASCN" ], 
		["II",    "BFO " ], 
		["II",    "BORG" ], 
		["II",    "BRVK" ], 
		["II",    "CMLA" ], 
		["II",    "COCO" ], 
		["II",    "DGAR" ], 
		["II",    "EFI " ], 
		["II",    "ERM " ], 
		["II",    "ESK " ], 
		["II",    "FFC " ], 
		["II",    "HOPE" ], 
		["II",    "JTS " ], 
		["II",    "KAPI" ], 
		["II",    "KDAK" ], 
		["II",    "KIV " ], 
		["II",    "KURK" ], 
		["II",    "KWAJ" ], 
		["II",    "LVZ " ], 
		["II",    "MBAR" ], 
		["II",    "MSEY" ], 
		["II",    "MSVF" ], 
		["II",    "NIL " ], 
		["II",    "NNA " ], 
		["II",    "NRIL" ], 
		["II",    "OBN " ], 
		["II",    "PALK" ], 
		["II",    "PFO " ], 
		["II",    "RAYN" ], 
		["II",    "RPN " ], 
		["II",    "SACV" ], 
		["II",    "SHEL" ], 
		["II",    "SUR " ], 
		["II",    "TAU " ], 
		["II",    "TLY " ], 
		["II",    "WRAB" ], 
		["IM",    "NV31" ], 
		["IM",    "PD31" ], 
		["IM",    "TX31" ], 
		["IU",    "ADK " ], 
		["IU",    "AFI " ], 
		["IU",    "ANMO" ], 
		["IU",    "ANTO" ], 
		["IU",    "BBSR" ],
		["IU",    "BILL" ], 
		["IU",    "CASY" ], 
		["IU",    "CCM " ], 
		["IU",    "CHTO" ], 
		["IU",    "COLA" ], 
		["IU",    "COR " ], 
		["IU",    "CTAO" ], 
		["IU",    "DAV " ], 
		["IU",    "DWPF" ], 
		["IU",    "FUNA" ], 
		["IU",    "FURI" ], 
		["IU",    "GNI " ], 
		["IU",    "GRFO" ], 
		["IU",    "GUMO" ], 
		["IU",    "HKT " ], 
		["IU",    "HNR " ], 
		["IU",    "HRV " ], 
		["IU",    "INCN" ], 
		["IU",    "JOHN" ], 
		["IU",    "KBL " ], 
		["IU",    "KBS " ], 
		["IU",    "KEV " ], 
		["IU",    "KIEV" ], 
		["IU",    "KIP " ], 
		["IU",    "KMBO" ], 
		["IU",    "KNTN" ], 
		["IU",    "KONO" ], 
		["IU",    "KOWA" ], 
		["IU",    "LCO " ], 
		["IU",    "LSZ " ], 
		["IU",    "LVC " ], 
		["IU",    "MA2 " ], 
		["IU",    "MACI" ], 
		["IU",    "MAJO" ], 
		["IU",    "MAKZ" ], 
		["IU",    "MBWA" ], 
		["IU",    "MIDW" ], 
		["IU",    "MSKU" ], 
		["IU",    "NWAO" ], 
		["IU",    "OTAV" ], 
		["IU",    "PAB " ], 
		["IU",    "PAYG" ], 
		["IU",    "PET " ], 
		["IU",    "PMG " ], 
		["IU",    "PMSA" ], 
		["IU",    "POHA" ], 
		["IU",    "PTCN" ], 
		["IU",    "PTGA" ], 
		["IU",    "QSPA" ],   
		["IU",    "RAO " ], 
		["IU",    "RAR " ], 
		["IU",    "RCBR" ], 
		["IU",    "RSSD" ], 
		["IU",    "SAML" ], 
		["IU",    "SBA " ], 
		["IU",    "SDV " ], 
		["IU",    "SFJD" ], 
		["IU",    "SJG " ], 
		["IU",    "SLBS" ], 
		["IU",    "SNZO" ], 
		["IU",    "SSPA" ], 
		["IU",    "TARA" ], 
		["IU",    "TATO" ], 
		["IU",    "TEIG" ], 
		["IU",    "TIXI" ], 
		["IU",    "TRIS" ], 
		["IU",    "TRQA" ], 
		["IU",    "TSUM" ], 
		["IU",    "TUC " ], 
		["IU",    "ULN " ], 
		["IU",    "WAKE" ], 
		["IU",    "WCI " ], 
		["IU",    "WVT " ], 
		["IU",    "XMAS" ], 
		["IU",    "YAK " ], 
		["IU",    "YSS " ], 
		["UO",    "PINE" ], 
		["US",    "AAM " ], 
		["US",    "ACSO" ], 
		["US",    "AGMN" ], 
		["US",    "AHID" ], 
		["US",    "AMTX" ], 
		["US",    "BINY" ], 
		["US",    "BLA " ], 
		["US",    "BMO " ], 
		["US",    "BOZ " ], 
		["US",    "BRAL" ], 
		["US",    "BW06" ],    
		["US",    "CBKS" ], 
		["US",    "CBN " ], 
		["US",    "CNNC" ], 
		["US",    "COWI" ], 
		["US",    "DGMT" ], 
		["US",    "DUG " ], 
		["US",    "ECSD" ], 
		["US",    "EGAK" ], 
		["US",    "EGMT" ], 
		["US",    "ELK " ], 
		["US",    "ERPA" ], 
		["US",    "EYMN" ], 
		["US",    "GLMI" ], 
		["US",    "GOGA" ], 
		["US",    "HAWA" ], 
		["US",    "HDIL" ], 
		["US",    "HLID" ], 
		["US",    "HWUT" ], 
		["US",    "ISCO" ], 
		["US",    "JCT " ], 
		["US",    "JFWS" ], 
		["US",    "KSU1" ], 
		["US",    "KVTX" ], 
		["US",    "LAO " ], 
		["US",    "LBNH" ], 
		["US",    "LKWY" ],     
		["US",    "LONY" ], 
		["US",    "LRAL" ], 
		["US",    "MCWV" ], 
		["US",    "MIAR" ], 
		["US",    "MNTX" ], 
		["US",    "MSO " ], 
		["US",    "MVCO" ], 
		["US",    "NATX" ], 
		["US",    "NEW " ], 
		["US",    "NHSC" ], 
		["US",    "NLWA" ], 
		["US",    "OGNE" ], 
		["US",    "OXF " ], 
		["US",    "PKME" ], 
		["US",    "RLMT" ], 
		["US",    "SCIA" ], 
		["US",    "SDCO" ], 
		["US",    "TPNV" ], 
		["US",    "TZTN" ], 
		["US",    "VBMS" ], 
		["US",    "WMOK" ], 
		["US",    "WRAK" ], 
		["US",    "WUAZ" ],   
		["US",    "WVOR" ],   
		["UU",    "CCUT" ],   
		["UU",    "SRU " ]
		]

from obspy.clients.fdsn import Client
c = Client("IRIS")
import ipdb;ipdb.set_trace()
inv = c.get_stations(network=GSN[0][0], station=GSN[0][1].strip())
for tup in GSN[1:]:
	inv += c.get_stations(network=tup[0],station=tup[1].strip())

def output_inventory_to_specfem_format(inventory,
                                       filename="master_station_list.txt"):
    """
    specfem requires station information in the form
    STATION NETWORK LATITUDE LONGITUDE ELEVATION BURIAL
    we can leave elevation and burial as 0.0 because our topography data takes
    care of elevation (stations assumed to be on the surface, which is
    approximately true. Take a stationxml and return a text file (no formatter)
    that contains the correct information
    :return:
    """
    template = ("{station:>6}{network:>6}    {latitude:6.4f}    "
                "{longitude:6.4f}    0.0    0.0\n"
                )
    with open(filename, 'w') as f:
        for net in inv:
            for sta in net:
                f.write(template.format(station=sta.code, network=net.code,
                                        latitude=sta.latitude,
                                        longitude=sta.longitude)
                        )

output_inventory_to_specfem_format(inv,filename='GSN.txt')
