event_tag: NAKTOMO
config_file: null
client: IRIS
client_debug: false
timeout: 600
taup_model: ak135
event_selection: default
origin_time: '2022-03-15T08:44:03.903000Z'
seconds_before_event: 20
seconds_after_event: 20
event_latitude: 69.69
event_longitude: -144.70
event_depth_km: 9.
event_magnitude: 4.
networks: '*'
stations: '*'
channels: BH?,HH?
locations: '*'
reference_time: '2022-03-15T08:44:03.903000Z'
seconds_before_ref: 100
seconds_after_ref: 500
phase_list: null
mindistance: 0
maxdistance: 20000.0
minazimuth: 0
maxazimuth: 360
minlatitude: 66.
maxlatitude: 77.
minlongitude: -151.
maxlongitude: -140.
demean: true
detrend: true
taper_percentage: 0
rotate:
- ZNE
- RTZ
remove_response: true
output_unit: VEL
water_level: 60
pre_filt: default
scale_factor: 1
resample_freq: null
remove_clipped: false
log_level: DEBUG
kwargs: {}
